dist: bionic
language: python

services:
  - docker

matrix:
  include:
    - python: 3.7
      env: TOX_ENV=py37-pr
      name: "tests check for PR"
    - python: 3.7
      env: TOX_ENV=flake8
      name: "flake8 check (linting)"
    - python: 3.7
      env: TOX_ENV=black
      name: "black check (code format)"

before_install:
  - if [ "${TOX_ENV}" == py37-pr ]; then 
      sh run_selenium_grid.sh; 
    fi

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

script:
- tox -e $TOX_ENV
